# Generated by Django 5.0.1 on 2024-02-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0002_books_geners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Geners',
            field=models.CharField(choices=[('crime', 'Crime'), ('adventure', 'Adventure'), ('action', 'Action'), ('suspense', 'Suspense')], default='action', max_length=30),
        ),
    ]
