# Generated by Django 5.0.1 on 2024-02-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0003_alter_books_geners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Geners',
            field=models.CharField(choices=[('action', 'Action'), ('suspense', 'Suspense'), ('crime', 'Crime'), ('adventure', 'Adventure')], default='action', max_length=30),
        ),
        migrations.AlterField(
            model_name='userid',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], default='teacher', max_length=10),
        ),
    ]
