# Generated by Django 5.0.1 on 2024-02-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0004_alter_books_geners_alter_userid_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Geners',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('action', 'Action'), ('crime', 'Crime'), ('suspense', 'Suspense')], default='action', max_length=30),
        ),
    ]
