# Generated by Django 5.0.1 on 2024-02-02 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0006_alter_books_geners_alter_userid_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Geners',
            field=models.CharField(choices=[('action', 'Action'), ('suspense', 'Suspense'), ('adventure', 'Adventure'), ('crime', 'Crime')], default='action', max_length=30),
        ),
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('denied', 'Denied'), ('accepted', 'Accepted'), ('return', 'Returned'), ('requested', 'Requested')], default='requested', max_length=30)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_management.books')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_by', to=settings.AUTH_USER_MODEL)),
                ('generated_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
