# Generated by Django 5.0.1 on 2024-02-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0007_alter_books_geners_bookrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('return', 'Returned'), ('denied', 'Denied'), ('accepted', 'Accepted'), ('requested', 'Requested')], default='requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='Geners',
            field=models.CharField(choices=[('suspense', 'Suspense'), ('crime', 'Crime'), ('adventure', 'Adventure'), ('action', 'Action')], default='action', max_length=30),
        ),
    ]
