# Generated by Django 5.0.1 on 2024-02-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0008_alter_bookrequest_status_alter_books_geners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('return', 'Returned'), ('requested', 'Requested'), ('denied', 'Denied'), ('accepted', 'Accepted')], default='requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='Geners',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('crime', 'Crime'), ('suspense', 'Suspense'), ('action', 'Action')], default='action', max_length=30),
        ),
    ]
