# Generated by Django 5.0.1 on 2024-02-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0013_alter_bookrequest_status_alter_books_geners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('return', 'Returned'), ('accepted', 'Accepted'), ('denied', 'Denied'), ('requested', 'Requested')], max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='Geners',
            field=models.CharField(choices=[('suspense', 'Suspense'), ('crime', 'Crime'), ('adventure', 'Adventure'), ('action', 'Action')], default='action', max_length=30),
        ),
    ]
