# Generated by Django 5.0.1 on 2024-02-09 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0014_alter_bookrequest_status_alter_books_geners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_management.books', unique=True),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('denied', 'Denied'), ('return', 'Returned'), ('requested', 'Requested'), ('accepted', 'Accepted')], default='requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='Geners',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('crime', 'Crime'), ('suspense', 'Suspense')], default='action', max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='Name_Of_Book',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
