# Generated by Django 5.0.1 on 2024-02-09 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0015_alter_bookrequest_book_alter_bookrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book_management.books'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('return', 'Returned'), ('denied', 'Denied'), ('accepted', 'Accepted')], default='requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='Geners',
            field=models.CharField(choices=[('crime', 'Crime'), ('adventure', 'Adventure'), ('action', 'Action'), ('suspense', 'Suspense')], default='action', max_length=30),
        ),
    ]
