# Generated by Django 5.0.1 on 2024-02-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0019_alter_bookrequest_status_alter_books_geners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('denied', 'Denied'), ('return', 'Returned'), ('accepted', 'Accepted'), ('requested', 'Requested')], default='requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='Geners',
            field=models.CharField(choices=[('action', 'Action'), ('crime', 'Crime'), ('suspense', 'Suspense'), ('adventure', 'Adventure')], default='action', max_length=30),
        ),
    ]
