# Generated by Django 5.0.1 on 2024-02-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0020_alter_bookrequest_status_alter_books_geners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('denied', 'Denied'), ('return', 'Returned'), ('requested', 'Requested')], default='requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='Geners',
            field=models.CharField(choices=[('crime', 'Crime'), ('adventure', 'Adventure'), ('suspense', 'Suspense'), ('action', 'Action')], default='action', max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='Name_Of_Book',
            field=models.CharField(max_length=50),
        ),
    ]
