# Generated by Django 5.0.1 on 2024-02-09 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0021_alter_bookrequest_status_alter_books_geners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_management.books'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('denied', 'Denied'), ('accepted', 'Accepted'), ('return', 'Returned'), ('requested', 'Requested')], default='requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='Geners',
            field=models.CharField(choices=[('suspense', 'Suspense'), ('adventure', 'Adventure'), ('crime', 'Crime'), ('action', 'Action')], default='action', max_length=30),
        ),
    ]
