# Generated by Django 5.0.1 on 2024-02-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0022_alter_bookrequest_book_alter_bookrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('return', 'Returned'), ('requested', 'Requested'), ('denied', 'Denied'), ('accepted', 'Accepted')], default='requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='Geners',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('suspense', 'Suspense'), ('crime', 'Crime')], default='action', max_length=30),
        ),
    ]
