# Generated by Django 5.0.1 on 2024-02-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0024_alter_bookrequest_status_alter_books_geners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('return', 'Returned'), ('denied', 'Denied'), ('accepted', 'Accepted')], default='requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='Geners',
            field=models.CharField(choices=[('crime', 'Crime'), ('suspense', 'Suspense'), ('action', 'Action'), ('adventure', 'Adventure')], default='action', max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
