# Generated by Django 5.0.1 on 2024-02-15 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0026_alter_bookrequest_status_alter_books_geners_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_name', models.CharField(max_length=23)),
                ('player_name', models.CharField(max_length=23)),
            ],
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('denied', 'Denied'), ('requested', 'Requested'), ('accepted', 'Accepted'), ('return', 'Returned')], default='requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='Geners',
            field=models.CharField(choices=[('crime', 'Crime'), ('adventure', 'Adventure'), ('suspense', 'Suspense'), ('action', 'Action')], default='action', max_length=30),
        ),
        migrations.CreateModel(
            name='men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_type', models.CharField(choices=[('player', 'Player'), ('coach', 'Coach')], max_length=23)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_management.sports')),
            ],
        ),
    ]
