# Generated by Django 5.0.1 on 2024-02-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0028_alter_bookrequest_status_alter_books_geners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('denied', 'Denied'), ('return', 'Returned'), ('requested', 'Requested'), ('accepted', 'Accepted')], default='requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='Geners',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('crime', 'Crime'), ('action', 'Action'), ('suspense', 'Suspense')], default='action', max_length=30),
        ),
        migrations.AlterField(
            model_name='men',
            name='player_type',
            field=models.CharField(choices=[('player', 'Player'), ('coach', 'Coach')], max_length=23),
        ),
    ]
